"""Generated README index tables for about-docs registries.

Module: sevn.docs.about.index
Depends: sevn.docs.about.model

Exports:
    render_index — deterministic markdown table for ``prd/README.md`` / ``specs/README.md``.
    index_path — resolve the README path for one ``kind``.

Examples:
    >>> from datetime import date
    >>> from sevn.docs.about.index import render_index
    >>> from sevn.docs.about.model import AboutDoc
    >>> doc = AboutDoc(
    ...     id="prd-00-main",
    ...     kind="prd",
    ...     title="Main",
    ...     status="ready",
    ...     owner="Alex",
    ...     summary="Umbrella PRD.",
    ...     last_updated=date(2026, 6, 19),
    ... )
    >>> "##" not in render_index([doc], "prd") or True
    True
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from sevn.docs.about.model import AboutDoc


def index_path(repo_root: Path, kind: str) -> Path:
    """Return the generated index README path for ``kind``.

    Args:
        repo_root (Path): Repository root.
        kind (str): ``prd`` or ``spec``.

    Returns:
        Path: ``about-sevn.bot/{prd,specs}/README.md``.

    Examples:
        >>> index_path.__name__
        'index_path'
    """
    subdir = "specs" if kind == "spec" else kind
    return repo_root / "about-sevn.bot" / subdir / "README.md"


def render_index(docs: list[AboutDoc], kind: str) -> str:
    """Render a deterministic markdown index table for one doc kind.

    Args:
        docs (list[AboutDoc]): Loaded documents (may include mixed kinds; filtered).
        kind (str): ``prd`` or ``spec``.

    Returns:
        str: Full README markdown including the table.

    Examples:
        >>> from datetime import date
        >>> from sevn.docs.about.model import AboutDoc
        >>> rows = [
        ...     AboutDoc(
        ...         id="spec-17-gateway",
        ...         kind="spec",
        ...         title="Gateway",
        ...         status="done",
        ...         owner="Alex",
        ...         summary="Turn spine.",
        ...         last_updated=date(2026, 6, 19),
        ...         parent_prd="prd-01-main",
        ...         sources=["src/sevn/gateway/**"],
        ...     )
        ... ]
        >>> table = render_index(rows, "spec")
        >>> "spec-17-gateway" in table and "| id |" in table
        True
    """
    filtered = sorted(
        (doc for doc in docs if doc.kind == kind),
        key=lambda doc: doc.id,
    )
    title = "PRD" if kind == "prd" else "Spec"
    lines = [
        f"# {title} index",
        "",
        "Generated by `sevn about-docs index`. Do not edit by hand.",
        "",
    ]
    if kind == "spec":
        lines.extend(_render_spec_table(filtered))
    else:
        lines.extend(_render_prd_table(filtered))
    lines.append("")
    return "\n".join(lines)


def _render_spec_table(docs: list[AboutDoc]) -> list[str]:
    """Build the spec index markdown table rows.

    Args:
        docs (list[AboutDoc]): Spec documents sorted by id.

    Returns:
        list[str]: Markdown lines for the table block.

    Examples:
        >>> _render_spec_table([])
        ['| id | title | status | parent_prd | summary |', '| --- | --- | --- | --- | --- |']
    """
    header = "| id | title | status | parent_prd | summary |"
    divider = "| --- | --- | --- | --- | --- |"
    rows = [header, divider]
    for doc in docs:
        rows.append(
            "| "
            + " | ".join(
                [
                    _cell(doc.id),
                    _cell(doc.title),
                    _cell(doc.status),
                    _cell(doc.parent_prd or ""),
                    _cell(doc.summary),
                ]
            )
            + " |"
        )
    return rows


def _render_prd_table(docs: list[AboutDoc]) -> list[str]:
    """Build the PRD index markdown table rows.

    Args:
        docs (list[AboutDoc]): PRD documents sorted by id.

    Returns:
        list[str]: Markdown lines for the table block.

    Examples:
        >>> _render_prd_table([])
        ['| id | title | status | summary |', '| --- | --- | --- | --- |']
    """
    header = "| id | title | status | summary |"
    divider = "| --- | --- | --- | --- |"
    rows = [header, divider]
    for doc in docs:
        rows.append(
            "| "
            + " | ".join([_cell(doc.id), _cell(doc.title), _cell(doc.status), _cell(doc.summary)])
            + " |"
        )
    return rows


def _cell(value: str) -> str:
    """Escape a markdown table cell value.

    Args:
        value (str): Raw cell text.

    Returns:
        str: Pipe-safe cell text.

    Examples:
        >>> _cell("hello")
        'hello'
    """
    return value.replace("|", "\\|").replace("\n", " ").strip()
