"""Tests for R3 extended RichBlock builders and fixture rendering."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from sevn.channels.telegram_rich import render_markdown_to_rich_message
from sevn.channels.telegram_rich_blocks import (
    build_anchor,
    build_animation,
    build_audio,
    build_caption,
    build_collage,
    build_details,
    build_footer,
    build_math,
    build_photo,
    build_pull_quotation,
    build_slideshow,
    build_table,
    build_table_cell,
    build_thinking,
    build_video,
    build_voice_note,
    resolve_media_source,
    rich_text_plain,
)

_FIXTURES = Path(__file__).resolve().parent.parent / "fixtures" / "telegram_rich"


def _load(name: str) -> str:
    return (_FIXTURES / name).read_text(encoding="utf-8")


def _first_block(msg: dict[str, Any]) -> dict[str, Any]:
    return msg["blocks"][0]


def test_table_alignment_and_caption_matches_skeleton() -> None:
    source = _load("table_aligned.md")
    msg = render_markdown_to_rich_message(source)
    skeleton = json.loads(_load("expected_table_skeleton.json"))
    assert msg == skeleton


def test_details_block_fixture() -> None:
    msg = render_markdown_to_rich_message(_load("details_block.md"))
    block = _first_block(msg)
    assert block["type"] == "details"
    assert block["summary"]["text"][0]["text"] == "More"
    assert block["body"][0]["type"] == "paragraph"
    assert "Hidden" in block["body"][0]["text"]["text"][0]["text"]


def test_math_block_fixture() -> None:
    msg = render_markdown_to_rich_message(_load("math_block.md"))
    types = [block["type"] for block in msg["blocks"]]
    assert types == ["paragraph", "math"]
    assert msg["blocks"][1]["text"] == "E = mc^2"


def test_photo_media_fixture() -> None:
    msg = render_markdown_to_rich_message(_load("media_photo.md"))
    block = _first_block(msg)
    assert block == {
        "type": "photo",
        "photo": {"file_id": "AgACAgIAAxkBAAI"},
        "caption": {"text": {"text": [{"type": "text", "text": "Diagram caption"}]}},
    }


def test_media_directive_fixture_all_kinds() -> None:
    msg = render_markdown_to_rich_message(_load("media_directives.md"))
    types = [block["type"] for block in msg["blocks"]]
    assert types == ["video", "audio", "voice", "animation"]
    assert msg["blocks"][0]["video"] == {"path": "/tmp/clip.mp4"}
    assert msg["blocks"][0]["caption"]["text"]["text"][0]["text"] == "Clip"
    assert msg["blocks"][1]["audio"] == {"file_id": "CQACAgIAAxkBAAI"}
    assert msg["blocks"][2]["voice"] == {"path": "/tmp/note.ogg"}
    assert msg["blocks"][3]["animation"] == {"path": "/tmp/loop.gif"}


def test_slideshow_fixture() -> None:
    msg = render_markdown_to_rich_message(_load("slideshow.md"))
    block = _first_block(msg)
    assert block["type"] == "slideshow"
    assert len(block["slides"]) == 2
    assert block["slides"][0]["photo"] == {"file_id": "AgACAgIAAxkBAA1"}
    assert block["slides"][1]["photo"] == {"path": "screenshots/two.png"}


def test_collage_fixture() -> None:
    msg = render_markdown_to_rich_message(_load("collage.md"))
    block = _first_block(msg)
    assert block["type"] == "collage"
    assert len(block["media"]) == 2
    assert block["media"][0]["photo"]["file_id"] == "A1"


def test_pull_quote_fixture() -> None:
    msg = render_markdown_to_rich_message(_load("pull_quote.md"))
    block = _first_block(msg)
    assert block["type"] == "pull_quote"
    assert "Pull quote line one" in block["text"]["text"][0]["text"]


def test_thinking_footer_anchor_fixtures() -> None:
    thinking = _first_block(render_markdown_to_rich_message(_load("thinking.md")))
    assert thinking["type"] == "thinking"
    assert thinking["collapsed"] is True
    assert "Reasoning step one" in thinking["text"]["text"][0]["text"]

    footer = _first_block(render_markdown_to_rich_message(_load("footer.md")))
    assert footer["type"] == "footer"
    assert footer["text"]["text"][0]["text"] == "Generated by sevn.bot"

    anchor = _first_block(render_markdown_to_rich_message(_load("anchor.md")))
    assert anchor == {"type": "anchor", "id": "section-ref"}


def test_builder_doctest_shapes() -> None:
    cell = build_table_cell(rich_text_plain("A"), align="center")
    assert cell["align"] == "center"
    table = build_table([[cell]], caption=build_caption(rich_text_plain("cap")))
    assert table["caption"]["text"]["text"][0]["text"] == "cap"
    assert build_math("x") == {"type": "math", "text": "x"}
    assert build_photo({"file_id": "X"})["photo"]["file_id"] == "X"
    assert build_video({"path": "/v"})["type"] == "video"
    assert build_audio({"file_id": "A"})["type"] == "audio"
    assert build_voice_note({"path": "/n"})["type"] == "voice"
    assert build_animation({"path": "/g"})["type"] == "animation"
    slide = build_photo({"file_id": "S"})
    assert build_slideshow([slide])["slides"][0]["type"] == "photo"
    assert build_collage([slide])["media"][0]["type"] == "photo"
    assert build_pull_quotation(rich_text_plain("q"))["type"] == "pull_quote"
    assert build_footer(rich_text_plain("f"))["type"] == "footer"
    assert build_anchor("id") == {"type": "anchor", "id": "id"}
    assert build_thinking(rich_text_plain("t"))["collapsed"] is True
    details = build_details(
        rich_text_plain("sum"),
        [build_photo({"file_id": "P"})],
    )
    assert details["type"] == "details"


def test_resolve_media_source_variants() -> None:
    assert resolve_media_source("file_id:ABC") == {"file_id": "ABC"}
    assert resolve_media_source("https://ex.example/x.jpg") == {
        "url": "https://ex.example/x.jpg",
    }
    assert resolve_media_source("/tmp/x.jpg") == {"path": "/tmp/x.jpg"}


def test_smoke_post_split_telegram_rich_blocks_surface() -> None:
    """W4: rich block builders remain importable from ``telegram_rich_blocks``."""
    import importlib

    mod = importlib.import_module("sevn.channels.telegram_rich_blocks")
    assert callable(getattr(mod, "build_slideshow", None))
